### Create User
POST http://localhost:8080/neo4j/users
Content-Type: application/json

{
  "userId": 10000007,
  "username": "username7",
  "fullName": "User7"
}


### Create Post
POST http://localhost:8080/neo4j/posts/10000003
Content-Type: application/json

{
  "postId": 10000003,
  "mediaType": "PHOTO",
  "caption": "This is first post of third user"
}


### Follow user
POST http://localhost:8080/neo4j/follow/10000001
Content-Type: application/json

{
  "userId": 10000007
}

### Get user followers
GET http://localhost:8080/neo4j/followers/10000003
Content-Type: application/json


### Get user following
GET http://localhost:8080/neo4j/following/10000003
Content-Type: application/json

### Get user following
GET http://localhost:8080/neo4j/following/10000003
Content-Type: application/json

### Check if user is following another user
GET http://localhost:8080/neo4j/checkfollowing/10000002?userId=10000003
Content-Type: application/json