### Like a post
POST http://localhost:8080/likes/like/10000001
Content-Type: application/json

{
  "postId": 10000001
}

### Unlike a post
POST http://localhost:8080/likes/unlike/10000001
Content-Type: application/json

{
  "postId": 10000001
}

### Get post likers
GET http://localhost:8080/likes/likers/10000001
Content-Type: application/json

### Get total post likers
GET http://localhost:8080/likes/totallikers/10000001
Content-Type: application/json
