### Create a comment on post
POST http://localhost:8080/comments/create/10000001
Content-Type: application/json

{
  "commentId": 10000002,
  "postId": 10000002,
  "text": "This is first comment"
}

### Edit a comment on post
PATCH http://localhost:8080/comments/edit/10000001
Content-Type: application/json

{
  "commentId": 10000002,
  "text": "This is a edited comment"
}

### Delete a comment on post
DELETE http://localhost:8080/comments/delete/10000003
Content-Type: application/json

{
  "commentId": 10000003,
  "postId": 10000001
}

### Get post commenters
GET http://localhost:8080/comments/commenters/10000005
Content-Type: application/json

### Get total count of post commenters
GET http://localhost:8080/comments/totalcommenters/10000005
Content-Type: application/json
