### Follow user
POST http://localhost:8080/friendship/follow/10000001
Content-Type: application/json

{
  "userId": 10000002
}

### Unfollow user
POST http://localhost:8080/friendship/unfollow/10000002
Content-Type: application/json

{
  "userId": 10000003
}

### Get user followers
GET http://localhost:8080/friendship/followers/10000003
Content-Type: application/json

### Get user following
GET http://localhost:8080/friendship/following/10000001
Content-Type: application/json

### Check if user is following another user
GET http://localhost:8080/friendship/checkfollowing/10000002?userId=10000003
Content-Type: application/json