### Like a post
POST http://localhost:8080/likes/like/post/10000004
Content-Type: application/json

{
  "postId": 10000004
}

### Unlike a post
POST http://localhost:8080/likes/unlike/post/10000001
Content-Type: application/json

{
  "postId": 10000001
}

### Like a comment
POST http://localhost:8080/likes/like/comment/10000004
Content-Type: application/json

{
  "postId": 10000003,
  "commentId": 10000007
}

### Unlike a comment
POST http://localhost:8080/likes/unlike/comment/10000003
Content-Type: application/json

{
  "commentId": 10000007
}


### Get post likers
GET http://localhost:8080/likes/likers/post/10000001
Content-Type: application/json

### Get total post likers
GET http://localhost:8080/likes/totallikers/post/10000001
Content-Type: application/json


### Get comment likers
GET http://localhost:8080/likes/likers/comment/10000002?commentId=10000002
Content-Type: application/json

### Get total comment likers
GET http://localhost:8080/likes/totallikers/comment/10000002?commentId=10000002
Content-Type: application/json